services:
  antijob_bot:
    build: .
    depends_on:
      - redis
    env_file:
      - .env
    restart: on-failure
    networks:
      - antijob_bot
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
        mode: "non-blocking"
        max-buffer-size: "4m"

  redis:
    image: redis
    container_name: ${DB_HOST}
    command: redis-server --port ${DB_PORT} --requirepass ${DB_PASSWORD}
    expose:
      - ${DB_PORT}
    volumes:
      - redis:/data
    networks:
      - antijob_bot
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"
        mode: "non-blocking"
        max-buffer-size: "2m"

volumes:
  redis:

networks:
  antijob_bot:
