services:
  antijob_bot:
    build: .
    depends_on:
      - redis
    env_file:
      - .env
    restart: on-failure

  redis:
    image: redis
    container_name: ${DB_HOST}
    command: redis-server --port ${DB_PORT} --requirepass ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - redis:/data

volumes:
  redis:
