name: deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build production
    runs-on: ["self-hosted", "antijob-bot", "production"]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Prepare .env
        run: |
          cp .env.example .env
          sed -i \
            -e "s,^TOKEN=.*,TOKEN=${TOKEN}," \
            -e "s,^DB_PASSWORD=.*,DB_PASSWORD=${DB_PASSWORD}," \
            -e "s,^ADMINS=.*,ADMINS=${ADMINS}," \
            -e "s,^FEEDBACK_CHAT_ID=.*,FEEDBACK_CHAT_ID=${FEEDBACK_CHAT_ID}," \
          .env
        env:
          TOKEN: "${{ secrets.TOKEN }}"
          DB_PASSWORD: "${{ secrets.DB_PASSWORD }}"
          ADMINS: "${{ secrets.ADMINS }}"
          FEEDBACK_CHAT_ID: "${{ secrets.FEEDBACK_CHAT_ID }}"
      - name: Build image
        run: docker-compose build

  start:
    name: Start production
    needs:
      - build
    runs-on: ["self-hosted", "antijob-bot", "production"]
    steps:
      - name: Start the app
        run: docker-compose up -d
