name: deployment

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      runType:
        description: "How to run this build?"
        required: true
        default: "default"
        type: choice
        options:
          - Force build
          - Default

jobs:
  deploy:
    name: Build and deploy production
    runs-on: [ "self-hosted", "antijob-bot", "production" ]
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Resolve image tag
        run: |
          if [ "${GITHUB_REF_TYPE}" = "tag" ]; then
            IMAGE_TAG="${GITHUB_REF_NAME#v}"
          else
            IMAGE_TAG="main-${GITHUB_SHA::7}"
          fi
          echo "IMAGE_TAG=${IMAGE_TAG}" >> "${GITHUB_ENV}"
          echo "Resolved IMAGE_TAG=${IMAGE_TAG}"
      - name: Prepare .env
        run: |
          cp .env.example .env
          sed -i \
            -e "s,^TOKEN=.*,TOKEN=${TOKEN}," \
            -e "s,^DB_PASSWORD=.*,DB_PASSWORD=${DB_PASSWORD}," \
            -e "s,^ADMINS=.*,ADMINS=${ADMINS}," \
            -e "s,^FEEDBACK_CHAT_ID=.*,FEEDBACK_CHAT_ID=${FEEDBACK_CHAT_ID}," \
          .env
        env:
          TOKEN: "${{ secrets.TOKEN }}"
          DB_PASSWORD: "${{ secrets.DB_PASSWORD }}"
          ADMINS: "${{ secrets.ADMINS }}"
          FEEDBACK_CHAT_ID: "${{ secrets.FEEDBACK_CHAT_ID }}"
      - name: Build image
        run: |
          docker build \
            -t "antijob_bot:${IMAGE_TAG}" \
            -t antijob_bot:main \
            .
      - name: Deploy stack
        run: IMAGE_TAG="${IMAGE_TAG}" docker stack deploy --compose-file docker-compose.prod.yml antijob_bot
